- name: Allow password-based login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication no$"
    line: "PasswordAuthentication yes"
    owner: root
    group: root

- name: Change Password for user ubuntu
  user: name=ubuntu password="{{ password_for_user_ubuntu | password_hash('sha512', 'saltdfjalsdf') }}" update_password=always

- name: Restart sshd
  service:
    name: ssh
    state: restarted

# ----------------------------------------------------
# Tag as success
# ----------------------------------------------------

- name: Set success fact
  set_fact:
    allow_password_success: True
